// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Din (
        ap_ready,
        data_in_read,
        in_cnt,
        d_in_i,
        d_in_o,
        d_in_o_ap_vld
);


output   ap_ready;
input  [7:0] data_in_read;
input  [2:0] in_cnt;
input  [31:0] d_in_i;
output  [31:0] d_in_o;
output   d_in_o_ap_vld;

reg[31:0] d_in_o;
reg d_in_o_ap_vld;

wire   [31:0] tmp_16_fu_86_p2;
wire   [0:0] tmp_fu_50_p2;
wire   [0:0] tmp_5_fu_60_p2;
wire   [0:0] tmp_9_fu_66_p2;
wire   [0:0] tmp_13_fu_72_p2;
wire   [31:0] tmp_12_fu_126_p3;
wire   [31:0] tmp_8_fu_168_p3;
wire   [31:0] tmp_s_fu_182_p1;
wire   [31:0] tmp_15_fu_78_p3;
wire   [23:0] tmp_21_fu_106_p1;
wire   [23:0] tmp_11_fu_98_p3;
wire   [7:0] tmp_20_fu_116_p4;
wire   [23:0] tmp_19_fu_110_p2;
wire   [15:0] tmp_18_fu_148_p1;
wire   [15:0] tmp_7_fu_140_p3;
wire   [15:0] tmp_17_fu_158_p4;
wire   [15:0] tmp_14_fu_152_p2;

always @ (*) begin
    if ((tmp_fu_50_p2 == 1'd1)) begin
        d_in_o = tmp_s_fu_182_p1;
    end else if (((tmp_5_fu_60_p2 == 1'd1) & (tmp_fu_50_p2 == 1'd0))) begin
        d_in_o = tmp_8_fu_168_p3;
    end else if (((tmp_9_fu_66_p2 == 1'd1) & (tmp_5_fu_60_p2 == 1'd0) & (tmp_fu_50_p2 == 1'd0))) begin
        d_in_o = tmp_12_fu_126_p3;
    end else if (((tmp_13_fu_72_p2 == 1'd1) & (tmp_9_fu_66_p2 == 1'd0) & (tmp_5_fu_60_p2 == 1'd0) & (tmp_fu_50_p2 == 1'd0))) begin
        d_in_o = tmp_16_fu_86_p2;
    end else begin
        d_in_o = d_in_i;
    end
end

always @ (*) begin
    if (((tmp_fu_50_p2 == 1'd1) | ((tmp_5_fu_60_p2 == 1'd1) & (tmp_fu_50_p2 == 1'd0)) | ((tmp_9_fu_66_p2 == 1'd1) & (tmp_5_fu_60_p2 == 1'd0) & (tmp_fu_50_p2 == 1'd0)) | ((tmp_13_fu_72_p2 == 1'd1) & (tmp_9_fu_66_p2 == 1'd0) & (tmp_5_fu_60_p2 == 1'd0) & (tmp_fu_50_p2 == 1'd0)))) begin
        d_in_o_ap_vld = 1'b1;
    end else begin
        d_in_o_ap_vld = 1'b0;
    end
end

assign ap_ready = 1'b1;

assign tmp_11_fu_98_p3 = {{data_in_read}, {16'd0}};

assign tmp_12_fu_126_p3 = {{tmp_20_fu_116_p4}, {tmp_19_fu_110_p2}};

assign tmp_13_fu_72_p2 = ((in_cnt == 3'd3) ? 1'b1 : 1'b0);

assign tmp_14_fu_152_p2 = (tmp_7_fu_140_p3 | tmp_18_fu_148_p1);

assign tmp_15_fu_78_p3 = {{data_in_read}, {24'd0}};

assign tmp_16_fu_86_p2 = (tmp_15_fu_78_p3 | d_in_i);

assign tmp_17_fu_158_p4 = {{d_in_i[31:16]}};

assign tmp_18_fu_148_p1 = d_in_i[15:0];

assign tmp_19_fu_110_p2 = (tmp_21_fu_106_p1 | tmp_11_fu_98_p3);

assign tmp_20_fu_116_p4 = {{d_in_i[31:24]}};

assign tmp_21_fu_106_p1 = d_in_i[23:0];

assign tmp_5_fu_60_p2 = ((in_cnt == 3'd1) ? 1'b1 : 1'b0);

assign tmp_7_fu_140_p3 = {{data_in_read}, {8'd0}};

assign tmp_8_fu_168_p3 = {{tmp_17_fu_158_p4}, {tmp_14_fu_152_p2}};

assign tmp_9_fu_66_p2 = ((in_cnt == 3'd2) ? 1'b1 : 1'b0);

assign tmp_fu_50_p2 = ((in_cnt == 3'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_182_p1 = data_in_read;

endmodule //Din
