webtalk_init -webtalk_dir C:/Users/Anant/OneDrive/Documents/Courses/NYU/ECE_GY_6463_Advanced_Hardware_Design/Week_1/Homework_1_Vivado/Homework_1_Vivado.sim/sim_1/behav/xsim/xsim.dir/Verilog_Quiz_VHDL_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 13 19:05:12 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c8283774-c1b7-4b40-9a68-2935c21f43a8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0ab8e2cef5f64123b1b2f7d65bdae2fc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2419646225 -regid "" -xml C:/Users/Anant/OneDrive/Documents/Courses/NYU/ECE_GY_6463_Advanced_Hardware_Design/Week_1/Homework_1_Vivado/Homework_1_Vivado.sim/sim_1/behav/xsim/xsim.dir/Verilog_Quiz_VHDL_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Anant/OneDrive/Documents/Courses/NYU/ECE_GY_6463_Advanced_Hardware_Design/Week_1/Homework_1_Vivado/Homework_1_Vivado.sim/sim_1/behav/xsim/xsim.dir/Verilog_Quiz_VHDL_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Anant/OneDrive/Documents/Courses/NYU/ECE_GY_6463_Advanced_Hardware_Design/Week_1/Homework_1_Vivado/Homework_1_Vivado.sim/sim_1/behav/xsim/xsim.dir/Verilog_Quiz_VHDL_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
