// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Dout (
        ap_ready,
        data_out,
        data_out_ap_vld,
        out_cnt,
        d_out
);


output   ap_ready;
output  [7:0] data_out;
output   data_out_ap_vld;
input  [2:0] out_cnt;
input  [31:0] d_out;

reg[7:0] data_out;
reg data_out_ap_vld;

wire   [0:0] tmp_fu_41_p2;
wire   [0:0] tmp_5_fu_51_p2;
wire   [0:0] tmp_8_fu_57_p2;
wire   [0:0] tmp_2_fu_63_p2;
wire   [7:0] tmp_15_fu_102_p1;

always @ (*) begin
    if ((tmp_fu_41_p2 == 1'd1)) begin
        data_out = tmp_15_fu_102_p1;
    end else if (((tmp_5_fu_51_p2 == 1'd1) & (tmp_fu_41_p2 == 1'd0))) begin
        data_out = {{d_out[15:8]}};
    end else if (((tmp_8_fu_57_p2 == 1'd1) & (tmp_5_fu_51_p2 == 1'd0) & (tmp_fu_41_p2 == 1'd0))) begin
        data_out = {{d_out[23:16]}};
    end else if (((tmp_2_fu_63_p2 == 1'd1) & (tmp_8_fu_57_p2 == 1'd0) & (tmp_5_fu_51_p2 == 1'd0) & (tmp_fu_41_p2 == 1'd0))) begin
        data_out = {{d_out[31:24]}};
    end else begin
        data_out = 'bx;
    end
end

always @ (*) begin
    if (((tmp_fu_41_p2 == 1'd1) | ((tmp_5_fu_51_p2 == 1'd1) & (tmp_fu_41_p2 == 1'd0)) | ((tmp_8_fu_57_p2 == 1'd1) & (tmp_5_fu_51_p2 == 1'd0) & (tmp_fu_41_p2 == 1'd0)) | ((tmp_2_fu_63_p2 == 1'd1) & (tmp_8_fu_57_p2 == 1'd0) & (tmp_5_fu_51_p2 == 1'd0) & (tmp_fu_41_p2 == 1'd0)))) begin
        data_out_ap_vld = 1'b1;
    end else begin
        data_out_ap_vld = 1'b0;
    end
end

assign ap_ready = 1'b1;

assign tmp_15_fu_102_p1 = d_out[7:0];

assign tmp_2_fu_63_p2 = ((out_cnt == 3'd3) ? 1'b1 : 1'b0);

assign tmp_5_fu_51_p2 = ((out_cnt == 3'd1) ? 1'b1 : 1'b0);

assign tmp_8_fu_57_p2 = ((out_cnt == 3'd2) ? 1'b1 : 1'b0);

assign tmp_fu_41_p2 = ((out_cnt == 3'd0) ? 1'b1 : 1'b0);

endmodule //Dout
